function graphErrorNewtonRaphson(YMatrix1)
%CREATEFIGURE(YMATRIX1)
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 23-Apr-2017 19:01:35

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
box(axes1,'on');
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(YMatrix1,'Parent',axes1);
set(plot1(1),'DisplayName','errores(:,1)');
set(plot1(2),'DisplayName','errores(:,2)');
set(plot1(3),'DisplayName','errores(:,3)');

% Create xlabel
xlabel('Iteracion');

% Create ylabel
ylabel('Errores');

% Create legend
legend(axes1,'show');
legend('x1','x2','x3');

