function createfigureAproxDirect(Y1, Y2, Y3)
%CREATEFIGURE(Y1, Y2, Y3)
%  Y1:  vector of y data
%  Y2:  vector of y data
%  Y3:  vector of y data

%  Auto-generated by MATLAB on 21-Apr-2017 15:22:48

% Create figure
figure1 = figure('Name','Metodos Directos');

% Create axes
axes1 = axes('Parent',figure1);
box(axes1,'on');
hold(axes1,'on');

% Create plot
plot(Y1,'*');

% Create plot
plot(Y2,'O');

% Create plot
plot(Y3,'X');


% Create xlabel
xlabel('Dato');

% Create ylabel
ylabel('Aproximacion');

% Create legend
legend(axes1,'show');
legend('LU','Cholesky','QR');

