function graphTDoolittleCholeskyGivens(time,f)
%CREATEFIGURE(YVECTOR1)
%  YVECTOR1:  bar yvector

%  Auto-generated by MATLAB on 02-May-2017 19:52:54

% Create figure
figure1 = figure('Name',f);

% Create axes
axes1 = axes('Parent',figure1);
box(axes1,'on');
hold(axes1,'on');

xlabel('Metodo');

% Create ylabel
ylabel('Tiempo (s)');

% Create bar
c = {'Doolittle','Cholesky','Givens'};
prices = [123 99 23];
bar(time)
set(gca, 'XTick', 1:5, 'XTickLabel', c);



