function graphTimeJacobiSeidelAllMatrix(tiempos,f)
%CREATEFIGURE(YVECTOR1)
%  YVECTOR1:  bar yvector

%  Auto-generated by MATLAB on 02-May-2017 19:52:54

% Create figure
figure1 = figure(f);

% Create axes
axes1 = axes('Parent',figure1);
box(axes1,'on');
hold(axes1,'on');

xlabel('Metodo');

% Create ylabel
ylabel('Tiempo (s)');

% Create bar
c = {'Jacobi289','Seidel289','Jacobi10089','Seidel10089','Jacobi4225','Seidel4225'};
prices = [123 99 23];
bar(tiempos)
set(gca, 'XTick', 1:6, 'XTickLabel', c);


