function graphTimeDirSinGivens(tiempos,t,name1,name2,name3,name4,f)
%CREATEFIGURE(YVECTOR1)
%  YVECTOR1:  bar yvector

%  Auto-generated by MATLAB on 02-May-2017 19:52:54

% Create figure
figure1 = figure('Name',f);

% Create axes
axes1 = axes('Parent',figure1);
box(axes1,'on');
hold(axes1,'on');

xlabel('Metodo');

% Create ylabel
ylabel('Tiempo (s)');
title(t);
% Create bar
c = {name1,name2,name3,name4};
bar(tiempos)
set(gca, 'XTick', 1:4, 'XTickLabel', c);
end
