function graphResultsNewtonRaphson(resultados)
%CREATEFIGURE(YMATRIX1)
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 23-Apr-2017 18:56:38

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
box(axes1,'on');
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(resultados,'Parent',axes1);
set(plot1(1),'DisplayName','raices(:,1)');
set(plot1(2),'DisplayName','raices(:,2)');
set(plot1(3),'DisplayName','raices(:,3)');

% Create xlabel
xlabel('Iteracion');

% Create ylabel
ylabel('Raices');

% Create legend
legend(axes1,'show');
legend('x1','x2','x3');
title("Aproximaciones newton raphson");

